context:
  version: 0.1.12

package:
  name: rf_diffusion_all_atom
  version: ${{ version }}

source:
    path: .

build:
  noarch: python 
  script: pip install . -v

requirements:
  host:
    - pip
    - python >=3.9,<3.10
    - setuptools
    - wheel
    - hatchling
  run:
    - aiohttp=3.9.3
    - aiosignal=1.2.0
    - annotated-types=0.6.0
    - antlr-python-runtime=4.9.3
    - aom=3.8.1
    - ase=3.22.1
    - assertpy=1.1
    - asttokens=2.4.1
    - async-timeout=4.0.3
    - attrs=23.1.0
    - backcall=0.2.0
    - biopython=1.78
    - blas=1.0
    - boost-cpp
    - brotli=1.1.0
    - brotli-bin=1.1.0
    - brotli-python=1.1.0
    - bzip2=1.0.8
    - c-ares
    - ca-certificates=2024.2.2
    - captum=0.6.0
    - certifi=2024.2.2
    - charset-normalizer=3.3.2
    - click=8.1.7
    - cloudpickle=2.2.1
    - colorama=0.4.6
    - contourpy=1.2.0
    - cuda-cudart=11.8.89
    - cuda-cupti=11.8.87
    - cuda-libraries=11.8.0
    - cuda-nvrtc=11.8.89
    - cuda-nvtx=11.8.86
    - cuda-runtime=11.8.0
    - cuda-version=11.8
    - cycler=0.12.1
    - cytoolz=0.12.2
    - dask-core=2023.11.0
    - dav1d=1.2.1
    - decorator=5.1.1
    - deepdiff=6.7.1
    - dgl=2.1.0.cu118
    - e3nn=0.5.1
    - exceptiongroup=1.2.0
    - executing=2.0.1
    - expat
    - ffmpeg
    - filelock=3.13.1
    - fire=0.5.0
    - flask=2.2.5
    - font-ttf-dejavu-sans-mono=2.37
    - font-ttf-inconsolata=3.000
    - font-ttf-source-code-pro=2.038
    - font-ttf-ubuntu=0.83
    - fontconfig
    - fonts-conda-ecosystem=1
    - fonts-conda-forge=1
    - fonttools=4.49.0
    - freetype
    - fribidi=1.0.10
    - frozenlist=1.4.0
    - fsspec=2023.10.0
    - gdk-pixbuf
    - gettext=0.21.1
    - giflib=5.2.1
    - gmp=6.3.0
    - gmpy2=2.1.2
    - gnutls
    - gobject-introspection=1.72.0
    - graphite2
    - graphviz
    - gtk2=2.24.33
    - gts=0.7.6
    - h5py
    - harfbuzz
    - hdf5=1.12.1
    - hydra-core=1.3.2
    - icecream=2.1.3
    - idna=3.6
    - imagecodecs-lite=2019.12.3
    - imageio
    - importlib-metadata=7.0.1
    - importlib-resources=6.1.2
    - ipython=8.18.1
    - isodate=0.6.1
    - itsdangerous=2.0.1
    - jedi=0.19.1
    - jinja2=3.1.3
    - joblib=1.2.0
    - kiwisolver=1.4.5
    - krb5
    - lame=3.100
    - lcms2
    - ld_impl_linux-64=2.40
    - lerc
    - libabseil=20240116.1
    - libass
    - libblas=3.9.0
    - libbrotlicommon=1.1.0
    - libbrotlidec=1.1.0
    - libbrotlienc=1.1.0
    - libcblas=3.9.0
    - libcublas=11.11.3.6
    - libcufft=10.9.0.58
    - libcufile=1.9.0.20
    - libcurand=10.3.5.119
    - libcurl
    - libcusolver=11.4.1.48
    - libcusparse=11.7.5.86
    - libdeflate
    - libdrm=2.4.120
    - libedit
    - libev=4.33
    - libexpat
    - libffi
    - libgcc-ng=13.2.0
    - libgfortran-ng=13.2.0
    - libgfortran5=13.2.0
    - libhwloc
    - libiconv
    - libidn2
    - libjpeg-turbo
    - liblapack=3.9.0
    - libllvm14
    - libnghttp2
    - libnpp
    - libnsl
    - libnvjpeg
    - libopenvino=2023.3.0
    - libopenvino-auto-batch-plugin=2023.3.0
    - libopenvino-auto-plugin=2023.3.0
    - libopenvino-hetero-plugin=2023.3.0
    - libopenvino-intel-cpu-plugin=2023.3.0
    - libopenvino-intel-gpu-plugin=2023.3.0
    - libopenvino-ir-frontend=2023.3.0
    - libopenvino-onnx-frontend=2023.3.0
    - libopenvino-paddle-frontend=2023.3.0
    - libopenvino-pytorch-frontend=2023.3.0
    - libopenvino-tensorflow-frontend=2023.3.0
    - libopenvino-tensorflow-lite-frontend=2023.3.0
    - libopus=1.3.1
    - libpciaccess=0.18
    - libpng
    - libprotobuf
    - librsvg
    - libsqlite
    - libssh2
    - libstdcxx-ng
    - libtasn1
    - libtool
    - libunistring=0.9.10
    - libuuid=2.38.1
    - libva=2.20.0
    - libvpx=1.13.1
    - libwebp
    - libwebp-base
    - libxcb
    - libxcrypt
    - libxml2
    - libzlib
    - lightning-utilities
    - llvm-openmp
    - llvmlite
    - locket
    - lz4-c
    - markupsafe
    - matplotlib-base
    - matplotlib-inline=0.1.6
    - mkl
    - mkl-service
    - mkl_fft
    - mkl_random
    - mpc
    - mpfr
    - mpmath
    - multidict
    - munkres
    - ncurses
    - nettle
    - networkx
    - ninja
    - nspr
    - nss
    - numba=0.59.0
    - numpy=1.26.4
    - ocl-icd
    - ocl-icd-system
    - omegaconf=2.3.0
    - openbabel=3.1.1
    - openh264
    - openjpeg
    - openssl
    - opt_einsum
    - opt_einsum_fx
    - ordered-set
    - orjson=3.9.15
    - p11-kit
    - packaging=23.2
    - pandas=2.2.1
    - pango
    - parso
    - partd
    - patsy
    - pcre2
    - pexpect
    - pickleshare=0.7.5
    - pillow
    - pip=24.0
    - pixman
    - poppler
    - poppler-data=0.4.11
    - prody
    - prompt-toolkit=3.0.43
    - psutil=5.9.8
    - pthread-stubs=0.4
    - ptyprocess=0.7.0
    - pugixml=1.14
    - pure_eval=0.2.2
    - pydantic=2.6.3
    - pydantic-core=2.16.3
    - pygments=2.17.2
    - pynndescent=0.5.10
    - pyparsing=3.1.1
    - pyrosetta=2024.10+release.2c36cbc
    - pysocks=1.7.1
    - python=3.9.18
    - python-dateutil=2.9.0
    - python-tzdata=2024.1
    - pytorch=2.2.1
    - pytorch-cuda=11.8
    - pytorch-mutex=1.0
    - pytorch_geometric=2.5.0
    - pytz=2024.1
    - pywavelets
    - pyyaml=6.0.1
    - rdflib=7.0.0
    - readline=8.2
    - requests=2.31.0
    - scikit-image=0.19.3
    - scikit-learn=1.3.0
    - scipy=1.12.0
    - seaborn
    - setuptools=69.1.1
    - six=1.16.0
    - snappy=1.1.10
    - sqlite=3.45.1
    - stack_data=0.6.2
    - statsmodels=0.14.0
    - svt-av1=1.8.0
    - sympy=1.12
    - tbb=2021.11.0
    - termcolor=2.4.0
    - threadpoolctl=2.2.0
    - tifffile=2020.6.3
    - tk=8.6.13
    - toolz=0.12.0
    - torchaudio=2.2.1
    - torchdata=0.7.1
    - torchmetrics=1.1.2
    - torchtriton=2.2.0
    - torchvision=0.17.1
    - tqdm=4.66.2
    - traitlets=5.14.1
    - trimesh=4.2.0
    - typing-extensions=4.10.0
    - tzdata=2024a
    - unicodedata2=15.1.0
    - urllib3=2.2.1
    - wcwidth=0.2.13
    - werkzeug=2.3.8
    - wheel=0.42.0
    - x264
    - x265=3.5
    - xz
    - yaml=0.2.5
    - yarl=1.9.3
    - zipp=3.17.0
    - zlib
    - zstd





#tests:
#  - python:
#      imports:
#        - rf_diffusion_all_atom 

about:
  homepage: https://github.com/Nylon-Hydrolase-Redesign/rf_diffusion_all_atom
  license: BSD-3-Clause
  license_file: LICENSE
  summary: rf_diffusion_all_atom
  description: |
    rf_diffusion_all_atom.
  documentation: https://github.com/Nylon-Hydrolase-Redesign/rf_diffusion_all_atom
